/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShelvesShelfIdRouteImport } from './routes/shelves.$shelfId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesShelfIdRoute = ShelvesShelfIdRouteImport.update({
  id: '/shelves/$shelfId',
  path: '/shelves/$shelfId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shelves/$shelfId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shelves/$shelfId'
  id: '__root__' | '/' | '/shelves/$shelfId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShelvesShelfIdRoute: typeof ShelvesShelfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/$shelfId': {
      id: '/shelves/$shelfId'
      path: '/shelves/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof ShelvesShelfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShelvesShelfIdRoute: ShelvesShelfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
